package com.den;

import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class Day1Test {

    // TODO autogenerated method stub
    @Test
    public void demo(){
        System.out.println("hello demo test!");
    }
}
